name: pipeline
channels:
- rdkit
- anaconda
- conda-forge
dependencies:
- rdkit==2017.09.02
- pandas==0.22.0
- luigi==2.7.5
- numpy==1.14.2
- psycopg2==2.7.4
- postgresql>=9.3
- django==2.0.5
- django-extensions==2.0.7
